### PR TITLE
Added some more products

### PR DESCRIPTION
**Pull request by DhanashriiNimbhorkar**

### CODE REVIEW

**Comment by adityanavgurukul** [comment]
Put images in separate folder. index.html file is missing.

**Comment by DhanashriiNimbhorkar** [comment]
Ok sir I'll do it.

**Comment by DhanashriiNimbhorkar** [comment]
but sir my file is not the main file, it's just a product page. How can I
change the name and if i'll add images in another folder then the images
will not be visible but i already have made the folder in that folder i've
added file and images. I've sent you the ss please do check it once

**Comment by adityanavgurukul** [comment]
@backendcoder2023 images should be in a seperate folder. Make the changes and push again. Message me on Discord if you have any doubt

**Comment by DhanashriiNimbhorkar** [comment]
Ok, I will do that.
Thank you

**Pull request closed without merging**
